name: CI For End to End Fake News Classifier MLOPS Pipelines

on:
  push
jobs:
    continuous-integration:
        runs-on: ubuntu-latest 

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: setup python env
              uses: actions/setup-python@v4
              with: 
                    python-version: 3.13
            - name: Cache pip dependencies
              uses: actions/cache@v3
              with:
                    path: ~/.cache/pip
                    key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
                    restore-keys: |
                        ${{ runner.os }}-pip-
            - name: Install dependencies
              run: | 
                    pip install -r requirements.txt


            - name: Set up DVC
              uses: iterative/setup-dvc@v1
            - name: Pre-download NLTK resources
              run: |
                python -m pip install nltk
                python -c "import nltk; nltk.download('stopwords'); nltk.download('punkt')"

            - name: run pipeline
              env:  
                    DB_NAME: ${{ secrets.DB_NAME }}
                    DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
                    MONGODB_URI: ${{ secrets.MONGODB_URI}}
                    MLFLOW_TRACKING_URI: ${{ secrets.MLFLOW_TRACKING_URI }}
                    CAPSTONE_TEST: ${{ secrets.CAPSTONE_TEST }}
              run: |
                    dvc repro
            - name: Reproduce Latest Model in-to production
              env:  
                CAPSTONE_TEST: ${{ secrets.CAPSTONE_TEST }}
              run: | 
                python scrpits/promote_model.py
